name       : msmtp
version    : 1.8.15
release    : 4
source     :
    - https://marlam.de/msmtp/releases/msmtp-1.8.15.tar.xz : 2265dc639ebf2edf3069fffe0a3bd76749f8b58f4001d5cdeae19873949099ce
homepage   : https://marlam.de/msmtp
license    : GPL-3.0-or-later
component  : network.clients
summary    : msmtp is an SMTP client
description: |
    msmtp is an easy to use SMTP client with fairly complete sendmail compatibility and supports profiles for use with different SMTP servers.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libsecret-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
