name       : msmtp
version    : 1.8.19
release    : 7
source     :
    - https://marlam.de/msmtp/releases/msmtp-1.8.19.tar.xz : 34a1e1981176874dbe4ee66ee0d9103c90989aa4dcdc4861e4de05ce7e44526b
homepage   : https://marlam.de/msmtp
license    : GPL-3.0-or-later
component  : network.clients
summary    : msmtp is an SMTP client
description: |
    msmtp is an easy to use SMTP client with fairly complete sendmail compatibility and supports profiles for use with different SMTP servers.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libsecret-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
