name       : msmtp
version    : 1.8.17
release    : 5
source     :
    - https://marlam.de/msmtp/releases/msmtp-1.8.17.tar.xz : 0fddbe74c1a9dcf6461b4a1b0db3e4d34266184500c403d7f107ad42db4ec4d3
homepage   : https://marlam.de/msmtp
license    : GPL-3.0-or-later
component  : network.clients
summary    : msmtp is an SMTP client
description: |
    msmtp is an easy to use SMTP client with fairly complete sendmail compatibility and supports profiles for use with different SMTP servers.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(libsecret-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
