name       : msmtp
version    : 1.6.6
release    : 1
source     :
    - https://pilotfiber.dl.sourceforge.net/project/msmtp/msmtp/1.6.6/msmtp-1.6.6.tar.xz : da15db1f62bd0201fce5310adb89c86188be91cd745b7cb3b62b81a501e7fb5e
license    : GPL-3.0
component  : network.clients
summary    : msmtp is an SMTP client
description: |
    msmtp is an SMTP client
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(openssl)
    - pkgconfig(libidn)
    - pkgconfig(libsecret-1)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
